"""JSON parser and validation utilities for AI responses."""

import json
import re
from typing import Any, Dict
from pydantic import ValidationError

from ai.schemas import MeetingSummary
from utils.logger import get_logger

logger = get_logger(__name__)


class JSONParsingError(Exception):
    """Raised when JSON parsing completely fails or output cannot be recovered."""


def clean_llm_json(raw_response: str) -> str:
    """Extract and clean raw JSON from LLM response.

    Handles markdown wraps (e.g. ```json ... ```) and removes leading/trailing whitespace.
    """
    cleaned = raw_response.strip()

    # Find first '{' and last '}'
    start_idx = cleaned.find("{")
    end_idx = cleaned.rfind("}")

    if start_idx != -1 and end_idx != -1 and end_idx > start_idx:
        cleaned = cleaned[start_idx : end_idx + 1]

    # Replace potential control characters
    cleaned = re.sub(r"[\x00-\x1F\x7F]", "", cleaned)

    return cleaned


def attempt_recovery(raw_json: str) -> str:
    """Applies regular expressions to recover from common JSON malformations.

    - Fixes trailing commas before closing braces/brackets.
    - Fixes double quotes inside strings.
    - Balances unclosed brackets if simple.
    """
    recovered = raw_json

    # Remove trailing commas from objects/arrays: e.g. [1, 2, ] -> [1, 2]
    recovered = re.sub(r",\s*([\]}])", r"\1", recovered)

    # Normalize multiple line breaks in strings
    recovered = re.sub(r"\n\s*\n", "\n", recovered)

    return recovered


def parse_and_validate(raw_response: str) -> MeetingSummary:
    """Clean, parse, recover, and validate raw text response into a Pydantic MeetingSummary.

    Args:
        raw_response: The raw string generated by the LLM.

    Returns:
        A validated MeetingSummary instance.

    Raises:
        JSONParsingError: If JSON cannot be parsed or does not validate against schema.
    """
    logger.debug("Starting JSON parsing and validation on raw content.")
    cleaned_json = clean_llm_json(raw_response)

    # Attempt 1: Standard JSON Load
    try:
        data = json.loads(cleaned_json)
        return MeetingSummary(**data)
    except (json.JSONDecodeError, ValidationError) as err:
        logger.warning("Attempt 1 parsing failed: %s. Initiating recovery procedures.", err)

    # Attempt 2: Recover common JSON issues
    recovered_json = attempt_recovery(cleaned_json)
    try:
        data = json.loads(recovered_json)
        return MeetingSummary(**data)
    except json.JSONDecodeError as err:
        logger.error("Attempt 2 JSON load failed: %s. Raw JSON segment: %s", err, recovered_json[:200])
        raise JSONParsingError(f"Could not parse valid JSON from response: {err}") from err
    except ValidationError as err:
        logger.error("Attempt 2 Pydantic validation failed: %s", err)
        raise JSONParsingError(f"JSON parsed but failed Pydantic validation: {err}") from err
